### ISSUE TITLE
How to generate score.npy file

### ISSUE THREAD

**Issue by AnastasiaBam** [pavancm/CONTRIQUE#13]
Using the provided datasets i am facing an issue regarding the regressor training. I have trained the model but i don't understand how the scores.npy file is generated

**Comment by pavancm** [comment]
scores.npy contain ground truth quality scores usually available in any public IQA datasets. This is only required to train the regressor in order to predict quality.

**Comment by yongZheng1723** [comment]
> score.npy 包含通常在任何公共 IQA 数据集中可用的基本事实质量分数。这只需要训练回归器以预测质量。

Can you share your score.npy file in this repository? So that we can measure the SROCC  and reproduce the results of your paper. Thank you very much!

**Comment by pavancm** [comment]
As mentioned in my previous comments scores.npy depends on which public IQA dataset you're employing. Since I don't own those datasets, I cannot share them here. You need to download respective IQA datasets and use the ground truth opinion scores available in them in scores.npy file.
