### ISSUE TITLE
About score.pny

### ISSUE THREAD

**Issue by yongZheng1723** [pavancm/CONTRIQUE#14]
Can you share your score.npy file in this repository? So that we can measure the SROCC and reproduce the results of your paper. Thank you very much!

**Comment by pavancm** [comment]
scores.npy file contains ground truth quality scores available in IQA datasets. I don't own any of the IQA datasets, so I cannot share them here. You can download and use any of the publicly available IQA datasets with ground truth quality scores stored in scores.npy.
