### ISSUE TITLE
KADIS-700 link is not working

### ISSUE THREAD

**Issue by Kowareta993** [pavancm/CONTRIQUE#16]
http://database.mmsp-kn.de/kadid-10k-database.html links are not working and alternative link ref_img folder is empty!
this data set is very important in your work, i don't know how to train the network without it.

**Comment by pavancm** [comment]
You need to check with the authors listed in the webpage about this issue. I don't own this dataset and had just used what was publicly available during this work. I also cannot publicly share this dataset since I don't own it and only if the authors of KADIS data agree, then I can share.

**Comment by Kowareta993** [comment]
thank you! they've introduced a mirror link.
