### ISSUE TITLE
About MS-colorspace

### ISSUE THREAD

**Issue by jczhydy** [pavancm/CONTRIQUE#17]
I have tried training for different color space,and get similar result in RGB、Graysacle.But I failed to get a good result in MS-colorspace.Is there are something special I should take into consider when training through MS-colorspace?And is large amount of data for pretraining essential?

**Comment by jczhydy** [comment]
When training only through MS-colorspace,I find trainloss decreases obviously faster than other colorspace,is it a normal phenomenon?

**Comment by jczhydy** [comment]
I may have idea,it may be overfitting,sorry for disturbing you!

**Comment by jczhydy** [comment]
Or is there are anything wrong in your code about MS transform?

**Comment by pavancm** [comment]
MS-color space as well as other color spaces are included to provide complementary information. Thus, using them as standalone does not give the best result. MS colorspace performs worse if you just use it without any other colorspace since it only contains high pass information which is not enough to make quality predictions particularly in UGC images since they are highly content dependent. You have to use multiple colorspaces simultaneously to achieve good performance.

**Comment by jczhydy** [comment]
And I want to know is local feature essential? Does it have important meaning for MS colorspace? I try to use RGB、Grayscale and MS colorspaces stimultaneously but its result is worse than using RGB、Grayscale simultaneously without using local feature

**Comment by pavancm** [comment]
Local features are beneficial for certain distortion types (might not be applicable to all artifacts). So the performance might degrade if your evaluation data is not sensitive to local changes.

**Comment by jczhydy** [comment]
You say just using MS colorspace for training performs worse,but in your paper just using the MS space performs much better than other colorspaces in UGC dataset.Both For KONIQ10k and SPAQ dataset,I can't get such result using MS colorspace  or combine with other colorspaces.

**Comment by pavancm** [comment]
I meant using MS space alone performs worse when compared to using multiple color spaces which is what we have shown in the paper.
Regarding results, we have reported the performance for KoNIQ-10k in the paper. If you're trying to replicate the experiments reported in the paper please email me directly indicating what issues you're facing along with the details.
