### ISSUE TITLE
The csv files are empty

### ISSUE THREAD

**Issue by xiaojifeng** [pavancm/CONTRIQUE#18]

**Comment by xiaojifeng** [comment]
I tried to run the command "wget -L https://utexas.box.com/shared/static/124n9sfb27chgt59o8mpxl7tomgvn2lo.csv -O csv_files/file_names_ugc.csv -q --show-progress" to download the csv files, but none of them have any content.

**Comment by pavancm** [comment]
Try downloading manually from the links provided in the readme. Sometimes wget might not download due to network issues. I cross checked once and the downloaded file is not empty for me.

**Comment by xiaojifeng** [comment]
The manual download works for me, thanks!
