### ISSUE TITLE
Data Organization for Model Training: Structure within Dataset Folders

### ISSUE THREAD

**Issue by chenyu1014** [pavancm/CONTRIQUE#24]
When training models, if the dataset is organized in a designated folder structure such as training_data/UGC_images/blur_image, would the blur_image folder only contain the images themselves or should it mirror the structure of a downloaded dataset, as seen in something like CERTH_ImageBlurDataset/EvaluationSet/DigitalBlurSet/ where additional subfolders or metadata files might also be present?

**Comment by pavancm** [comment]
The folder usually contains images but I guess you can change those in PyTorch.
