### ISSUE TITLE
interpret the score using the provided weight file

### ISSUE THREAD

**Issue by tuvovan** [pavancm/CONTRIQUE#25]
Hi,

I would like to use your code to assess my images for my own research. I followed the README file and download the weight file named CONTRIQUE_checkpoint25.tar and got the scores so far. I'm just curious about how to interpret these scores. is the higher the better?

thank you!

**Comment by pavancm** [comment]
Yes, generally higher score means better quality in most cases.

There are certain cases where the linear regressor is trained using DMOS (Difference mean opinion scores) in which case it is reversed i.e. lower score means better. Please make sure on what data the linear regressor was trained before interpreting them.
