### ISSUE TITLE
How to generate distorted images from kadis700k

### ISSUE THREAD

**Issue by chenyu1014** [pavancm/CONTRIQUE#26]
I see that the data provided by the official source is in MATLAB format. Do I need to run the generate_kadis700k.m file using MATLAB? How long approximately will it take?

**Comment by pavancm** [comment]
If you are in need of entire data then you have to run the generate_kadis700k.m on the entire set of images. Depending on your system configurations it could take quite sometime (I don't remember how long did it take when I generated, maybe around 1-2 days I think).

**Comment by yuweiiiii** [comment]
Hello, where can I download the generate_kadis700k.m file? I can't find it in the repository. Thank you very much for your answer！

**Comment by pavancm** [comment]
The file is available here https://database.mmsp-kn.de/kadid-10k-database.html
