### ISSUE TITLE
[Recommendation] Recommendation to provide link of synthesized image distortion scripts.

### ISSUE THREAD

**Issue by CaptainEven** [pavancm/CONTRIQUE#5]
In case of custom dataset training requirements, and to avoid downloading KaDID-30K dataset, it's recommended to provide the link of synthesizing image distortions  Matlab scripts. Because the dataset is so large(40+G)...

**Comment by pavancm** [comment]
The scripts for KADIS700k are available [here](http://database.mmsp-kn.de/kadid-10k-database.html). The dataset size is large since there are 140k reference images. Note that the downloaded file only contains reference images, no distorted images.

**Comment by CaptainEven** [comment]
@pavancm The scripts seems to be bundled with KADIS-700K, and has to be downloaded together with the 40+G dataset...

**Comment by pavancm** [comment]
You need to check with the authors of KADIS-700k about this since they are the original authors of the code. I am not legally allowed to share them since I have not written those codes.

**Comment by CaptainEven** [comment]
@pavancm Thanks for reminding!
