### ISSUE TITLE
The link of KADIS-700k dataset is dead

### ISSUE THREAD

**Issue by JarvisFei** [pavancm/CONTRIQUE#9]
How can I get the KADIS-700k dataset?

**Comment by pavancm** [comment]
The link seems to working for me http://database.mmsp-kn.de/kadid-10k-database.html
The link seems to be not secure (https), try accessing with just http

**Comment by Kowareta993** [comment]
I can't download it either
https://datasets.vqa.mmsp-kn.de/archives/kadis700k.zip is not working anymore
